version: "3"
services:
  web:
    build: site
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html/
      - ./server/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./server/apache2.conf:/etc/apache2/apache2.conf
      - ./server/php.ini:/usr/local/etc/php/php.ini

  database:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./script/sql/create_db/script_carte_chance.sql:/docker-entrypoint-initdb.d/script_carte_chance.sql
    environment:
      POSTGRES_DB: esgi
      POSTGRES_USER: esgi
      POSTGRES_PASSWORD: Test1234

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  sass:
    build: sass
    volumes:
      - ./www:/home
    command: sass --watch "/home/Assets/scss/main.scss:/home/style.css"

  mailcatcher:
    restart: always
    image: dockage/mailcatcher:0.8.2
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  pgdata:
