---
installation:
  done: true
  on-going: false
bdd:
  host: database
  dbname: esgi
  port: 5432
  username: esgi
  password: Test1234
  prefix: mapa
  user:
    pseudo: zaza
    firstname: zaza
    lastname: zazaz
    email: zaz@dz.Fr
    phone: 0676767861
    password: Azer123@
errorLog: explicit
website:
  name: aza
  description: zaza
  baseurl: http://localhost/
mail:
  mailer: smtp
  host: mailcatcher
  port: 1025
  mailFrom: aza@dz.Fr
...
