---
installation:
  done: false
  on-going: false
bdd:
  host: database
  dbname: esgi
  port: 5432
  username: esgi
  password: Test1234
  prefix: esgi
  user:
    pseudo: admin
    firstname: admin
    lastname: admin
    email: admin@admin.com
    phone: 0611111111
    password: test
errorLog: explicit
website:
  name: La Carte Chance
  description: Description
  baseurl: http://localhost/
mail:
  mailer: smtp
  host: mailcatcher
  port: 1025
  mailFrom: admin@admin.com
...
