---
installation:
  done: true
  on-going: false
bdd:
  host: database
  dbname: esgi
  port: 5432
  username: esgi
  password: Test1234
  prefix: esgi
  user:
    pseudo: Gauthier
    firstname: Gauthier
    lastname: LO
    email: lo.gauthier.glo@gmail.com
    phone: 0651957268
    password: Azerty1!
errorLog: explicit
website:
  name: Mon site
  description: Ma description&#039;
  baseurl: http://localhost/
mail:
  mailer: smtp
  host: mailcatcher
  port: 1025
  mailFrom: lo.gauthier.glo@gmail.com
...
