---
configEnd: true
bdd:
  host: database
  dbname: esgi
  port: 5432
  username: esgi
  password: Test1234
  prefix: carte_chance_
errorLog: explicit
website:
  name: La Carte Chance
  description: "Retrouvez tous vos jeux de soci\xE9t\xE9 pr\xE9f\xE9r\xE9s sur notre
    site !"
  baseurl: http://localhost/
...
