---
installation:
  done: false
  on-going: false
bdd:
  host: database
  dbname: esgi
  port: 5432
  username: esgi
  password: Test1234
  prefix: mapa
  user:
    pseudo: <script>alert("H");
    firstname: mathieu
    lastname: pannetrat
    email: mathieu@gmail.com
    phone: 0678787874
    password: Azerty123@
errorLog: explicit
website:
  name: le site de mathieu
  description: descrzszszez
  baseurl: http://localhost/
mail:
  mailer: smtp
  host: mailcatcher
  port: 1025
  mailFrom: mapa@gmail.com
...
