default:
  controller: Main
  action: home
  access: [ALL]

about-us:
  controller: Main
  action: aboutUs
  access: [ALL]

contact:
  controller: Main
  action: contact
  access: [ALL]

login:
  controller: Auth
  action: login
  access: [ALL]

logout:
  controller: Auth
  action: logout
  access: [ALL]

s-inscrire:
  controller: Auth
  action: register
  access: [ALL]

search:
  controller: Main
  action: search
  access: [ ALL ]

email-confirmation:
  controller: Auth
  action: emailConfirmation
  access: [ALL]

profil:
  controller: Auth
  action: profile
  access: [USER, MODERATOR, ADMIN]

edit-profile:
  controller: Auth
  action: editProfile
  access: [USER, MODERATOR, ADMIN]

reset-password:
  controller: Auth
  action: resetPassword
  access: [ALL]

jeux:
  controller: JeuxController
  action: allGames
  access: [ALL]
  jeu:
    controller: JeuxController
    action: oneGame
    access: [ALL]

articles:
  controller: Article
  action: allArticles
  access: [ALL]
  article:
    controller: Article
    action: oneArticle
    access: [ALL]

installer:
  controller: Installer
  action: installer
  access: [ALL]

  set-admin:
    controller: Installer
    action: setAdmin
    access: [ALL]

  set-database:
    controller: Installer
    action: setDatabase
    access: [ALL]

trucs-et-astuces:
  controller: Article
  action: allTrucsEtAstuces
  access: [ALL]

page:
  controller: ArticleController
  action: getArticle
  access: [ ALL ]
  allgames:
    controller: Article
    action: GetAllArticlesGame
    access: [ALL]

  allaboutgames:
    controller: Article
    action: GetAllArticlesAboutGame
    access: [ ALL ]

sys:
  user:
    list:
      controller: System
      action: userlist
      access: [ADMIN, MODERATOR]

  article:
    articles-management:
      controller: Article
      action: articlesManagement
      access: [ ADMIN, MODERATOR ]
    datatable:
      controller: Article
      action: articleDatatable
      access: [ ADMIN, MODERATOR ]
    create-article-game:
      controller: Article
      action: createArticleGame
      access: [ ADMIN, MODERATOR ]
    create-article-about-game:
      controller: Article
      action: createArticleAboutGame
      access: [ ADMIN, MODERATOR ]
    delete-article:
      controller: Article
      action: deleteArticle
      access: [ ADMIN, MODERATOR ]
    edit-article:
      controller: Article
      action: updateArticle
      access: [ ADMIN, MODERATOR ]
    get-all-article-version:
      controller: Article
      action: getAllArticlesMemento
      access: [ ADMIN, MODERATOR ]

  dashboard:
    controller: Dashboard
    action: index
    access: [ ADMIN, MODERATOR ]
  comment:
    list:
      controller: CommentController
      action: index
      access: [ ADMIN, MODERATOR ]
    edit:
      controller: CommentController
      action: edit
      params: [ id ]
      access: [ ADMIN, MODERATOR ]
    moderate:
      controller: CommentController
      action: moderate
      access: [ ADMIN, MODERATOR ]

api:
  user:
    add:
      controller: Api
      action: usercreate
      method: POST
      access: [ADMIN, MODERATOR]

    list:
      controller: Api
      action: userlist
      method: GET
      params: [length, start, search, draw]
      access: [ADMIN, MODERATOR]

    edit:
      controller: Api
      action: useredit
      method: POST
      access: [ADMIN]

    delete:
      controller: Api
      action: userdelete
      method: DELETE
      access: [ADMIN]

