default:
  controller: Main
  action: home

about-us:
  controller: Main
  action: aboutUs

contact:
  controller: Main
  action: contact

login:
  controller: Auth
  action: login

logout:
  controller: Auth
  action: logout

s-inscrire:
  controller: Auth
  action: register

email-confirmation:
  controller: Auth
  action: emailConfirmation

page:
  controller: Pages
  action: GetPage

page-managment:
  controller: Pages
  action: createPage