default:
  controller: Main
  action: home

a-propos:
  controller: Main
  action: aboutUs

about-us:
  controller: Main
  action: aboutUs

contact:
  controller: Main
  action: contact

login:
  controller: Auth
  action: login

logout:
  controller: Auth
  action: logout

s-inscrire:
  controller: Auth
  action: register

email-confirmation:
  controller: Auth
  action: emailConfirmation

sys:
  user:
    list:
      controller: System
      action: userlist
      access: admin, moderator
api:
  user:
    list:
      controller: Api
      action: userlist
      params: [length, start, search, draw]
      access: admin, moderator
    delete:
      controller: Api
      action: userdelete
      access: admin